/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author HP
 */
public class adminLogin extends javax.swing.JFrame {
     int interval;
     Timer timer;
    
    public adminLogin() {
        initComponents();
        stopwatch();
        adminname.requestFocus();
    }
    public void stopwatch(){
        int delay =1000;
        int period =1000;
        timer=new Timer();
        interval= 30;
        timer.scheduleAtFixedRate(new TimerTask() {
        public void run() {
            setInterval();
        }
    }, delay, period);
    }
    public int setInterval() {
    if (interval == 1){
        timer.cancel();
    System.exit(0);}
    return --interval;
        
}
   /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        adminPassWord = new javax.swing.JPasswordField();
        section = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        adminname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage your Power Mr. Admin!");
        setMaximumSize(new java.awt.Dimension(540, 475));
        setMinimumSize(new java.awt.Dimension(540, 475));
        setPreferredSize(new java.awt.Dimension(540, 475));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Show Yourself as The Admin !!!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 55, 350, 40));

        adminPassWord.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        adminPassWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminPassWordActionPerformed(evt);
            }
        });
        adminPassWord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                adminPassWordKeyPressed(evt);
            }
        });
        getContentPane().add(adminPassWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 220, 190, 40));

        section.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        section.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registration & HR", "Examinations", "Accounting" }));
        getContentPane().add(section, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 110, 190, 30));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText(" All Rights Reserved by UoM");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 170, 30));

        adminname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        adminname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                adminnameKeyPressed(evt);
            }
        });
        getContentPane().add(adminname, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 160, 190, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/QFK.gif"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminPassWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminPassWordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminPassWordActionPerformed

    private void adminPassWordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adminPassWordKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
           try{
               Conn.Database.getDatabaseConnection();
               PreparedStatement ps=Conn.Database.con.prepareStatement("Select adminid from admin where section =? and adminName=binary ? AND adminpassword=binary ? ");
               ps.setString(1, section.getSelectedItem().toString());
               ps.setString(2, adminname.getText());
               ps.setString(3,adminPassWord.getText());
               ResultSet rs=ps.executeQuery();
               if(rs.next()){
                   JOptionPane.showMessageDialog(this, "Do necessary Mr. Admin !       ");
                   timer.cancel();
                   switch (section.getSelectedIndex()) {
                       case 0:
                           DataManagement data=new DataManagement();
                           data.setVisible(true);
                           data.setLocationRelativeTo(null);
                           this.dispose();
                           School.sectionname=section.getSelectedItem().toString();
                           break;
                       case 1:
                           Exammanagement e=new Exammanagement();
                           e.setVisible(true);
                           e.setLocationRelativeTo(null);
                           this.dispose();
                           School.sectionname=section.getSelectedItem().toString();
                           break;
                       case 2:
                           SalaryManagement s=new SalaryManagement();
                           s.setVisible(true);
                           s.setLocationRelativeTo(null);
                           this.dispose();
                           School.sectionname=section.getSelectedItem().toString();
                           break;
                       default:
                           break;
                   }
               }else{
                  JOptionPane.showMessageDialog(this, "You are not welcomed !!!    ");
                  System.exit(0);
               }
           
           }catch(HeadlessException x){
               JOptionPane.showMessageDialog(this, "Error:\n"+x);
           }catch(SQLException ex){
               JOptionPane.showMessageDialog(this,"Error In SQL: \n"+ex);
           }  
       }
    }//GEN-LAST:event_adminPassWordKeyPressed

    private void adminnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adminnameKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            if(adminname.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Reveal your name, Mr. Admin  !     ");
            }else{
                adminPassWord.requestFocus();
            }
        }
    }//GEN-LAST:event_adminnameKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField adminPassWord;
    private javax.swing.JTextField adminname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> section;
    // End of variables declaration//GEN-END:variables
}
