/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school;

import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
//import java.sql.Date;
import java.util.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static school.School.M;
import static school.School.Y;
import static school.School.d;
import static school.School.h;
import static school.School.m;
import static school.School.s;

/**
 *
 * @author HP
 */
public class Exammanagement extends javax.swing.JFrame {
    interface Settingzerosh{
       StringBuilder ifelse(int h);
       Settingzerosh doifelseh=(int h) -> {
           StringBuilder HS=new StringBuilder(String.valueOf(h));
           if(HS.length()==1){
               HS.insert(0, "0");
               return HS;
           }else{
              return HS; 
           }
       };
}
 interface Settingzerosm{
       StringBuilder ifelse(int m);
       Settingzerosm doifelsem=(int m) -> {
           StringBuilder MS=new StringBuilder(String.valueOf(m));
           if(MS.length()==1){
               MS.insert(0, "0");
               return MS;
           }else{
              return MS; 
           }
       };
} 
 interface Settingzeross{
       StringBuilder ifelse(int s);
       Settingzeross doifelses=(int s) -> {
           StringBuilder SS=new StringBuilder(String.valueOf(s));
           if(SS.length()==1){
               SS.insert(0, "0");
               return SS;
           }else{
              return SS; 
           }
       };
}
    javax.swing.Timer t=new javax.swing.Timer(1000, new ClockListener());
    class ClockListener implements ActionListener{
            public void actionPerformed(ActionEvent e){
                Calendar now= Calendar.getInstance();
                d=now.get(Calendar.DAY_OF_MONTH);
                M=now.get(Calendar.MONTH);++M;
                Y=now.get(Calendar.YEAR);
                h=now.get(Calendar.HOUR_OF_DAY);
                m=now.get(Calendar.MINUTE);
                s=now.get(Calendar.SECOND);
                StringBuilder HS=Settingzerosh.doifelseh.ifelse(h);
                StringBuilder MS=Settingzerosm.doifelsem.ifelse(m);
                StringBuilder SS=Settingzeross.doifelses.ifelse(s);
                clock.setText(""+HS+":"+MS+":"+SS);
                date.setText(""+d+"/"+M+"/"+Y);
               
    }
    }

   
    public Exammanagement() {
        initComponents();
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        titleexam = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table3 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        clock = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        examM = new javax.swing.JButton();
        marksM = new javax.swing.JButton();
        paymentsM = new javax.swing.JButton();
        fundsM = new javax.swing.JButton();
        salaryM = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Table2 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        examgpa = new javax.swing.JTextField();
        txtFullName = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtmobile = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtUID = new javax.swing.JTextField();
        projectgpa = new javax.swing.JTextField();
        examname = new javax.swing.JTextField();
        examcode = new javax.swing.JTextField();
        examduration = new javax.swing.JTextField();
        examvenue = new javax.swing.JTextField();
        examid = new javax.swing.JTextField();
        catid = new javax.swing.JTextField();
        catname = new javax.swing.JTextField();
        catcode = new javax.swing.JTextField();
        catduration = new javax.swing.JTextField();
        catvenue = new javax.swing.JTextField();
        catgpa = new javax.swing.JTextField();
        projectid = new javax.swing.JTextField();
        projectname = new javax.swing.JTextField();
        projectcode = new javax.swing.JTextField();
        projectduration = new javax.swing.JTextField();
        projectvenue = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();
        Clearall = new javax.swing.JButton();
        catdate = new com.toedter.calendar.JDateChooser();
        examdate = new com.toedter.calendar.JDateChooser();
        projectdate = new com.toedter.calendar.JDateChooser();
        adminpasswordchange = new javax.swing.JButton();
        Logout7 = new javax.swing.JButton();
        inquiries = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Examanition Management at UoM");
        setMaximumSize(new java.awt.Dimension(1800, 1000));
        setMinimumSize(new java.awt.Dimension(1800, 1000));
        setPreferredSize(new java.awt.Dimension(1800, 1000));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("University of Moratuwa");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 60));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Wisdom is all wealth");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, 20));

        titleexam.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        titleexam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleexam.setText("Examinations Management");
        getContentPane().add(titleexam, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 70, 400, 50));

        Table3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        Table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Project ID", "User Name", "Project Name", "Project Code", "Date/Time", "Time Duration", "Venue", "GPA Fraction"
            }
        ));
        Table3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table3MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table3);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 1140, 130));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Search");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 100, -1, -1));

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 100, 400, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 140, 550, 10));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText(" All Rights Reserved by UoM");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 900, 160, -1));

        clock.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        clock.setText("00:00:00");
        getContentPane().add(clock, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 875, 60, -1));

        date.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        date.setText("Date");
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(1698, 875, 80, -1));

        examM.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        examM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user management.png"))); // NOI18N
        examM.setText(" User Management");
        examM.setBorderPainted(false);
        examM.setContentAreaFilled(false);
        examM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        examM.setEnabled(false);
        examM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examMActionPerformed(evt);
            }
        });
        getContentPane().add(examM, new org.netbeans.lib.awtextra.AbsoluteConstraints(1475, 650, 230, 40));

        marksM.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        marksM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/marks manage.png"))); // NOI18N
        marksM.setText(" Marks Management");
        marksM.setBorderPainted(false);
        marksM.setContentAreaFilled(false);
        marksM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        marksM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marksMActionPerformed(evt);
            }
        });
        getContentPane().add(marksM, new org.netbeans.lib.awtextra.AbsoluteConstraints(1475, 705, 230, 40));

        paymentsM.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        paymentsM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/payments manage.png"))); // NOI18N
        paymentsM.setText(" Payments Management");
        paymentsM.setBorderPainted(false);
        paymentsM.setContentAreaFilled(false);
        paymentsM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paymentsM.setEnabled(false);
        paymentsM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentsMActionPerformed(evt);
            }
        });
        getContentPane().add(paymentsM, new org.netbeans.lib.awtextra.AbsoluteConstraints(1475, 760, 270, 40));

        fundsM.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        fundsM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fund manage.png"))); // NOI18N
        fundsM.setText(" Funds Management");
        fundsM.setBorderPainted(false);
        fundsM.setContentAreaFilled(false);
        fundsM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fundsM.setEnabled(false);
        fundsM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundsMActionPerformed(evt);
            }
        });
        getContentPane().add(fundsM, new org.netbeans.lib.awtextra.AbsoluteConstraints(1475, 815, 240, 40));

        salaryM.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        salaryM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salary manage.jpg"))); // NOI18N
        salaryM.setText("Salary Management");
        salaryM.setBorderPainted(false);
        salaryM.setContentAreaFilled(false);
        salaryM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salaryM.setEnabled(false);
        salaryM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryMActionPerformed(evt);
            }
        });
        getContentPane().add(salaryM, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 890, 280, 50));

        Table1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Exam ID", "User Name", "Exam Name", "Exam Code", "Date/Time", "Time Duration", "Venue", "GPA Fraction"
            }
        ));
        Table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Table1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 1140, 130));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/University_of_Moratuwa_logo.png"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, 380));

        Table2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        Table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CAT ID", "User Name", "CAT Name", "CAT Code", "Date/Time", "Time Duration", "Venue", "GPA Fraction"
            }
        ));
        Table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table2MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(Table2);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 1140, 130));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("User name");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("UID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Full Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 290, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Email  Add");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Mobile No");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 230, -1, -1));

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsernameKeyPressed(evt);
            }
        });
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 170, 150, -1));

        examgpa.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        getContentPane().add(examgpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 580, 125, -1));

        txtFullName.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        getContentPane().add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 290, 300, -1));

        txtemail.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 170, 150, -1));

        txtmobile.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtmobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmobileActionPerformed(evt);
            }
        });
        getContentPane().add(txtmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 230, 150, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("GPA /F");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 580, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("ID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 400, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Projects");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 360, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Code");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 460, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Date/Time");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 490, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Time Duration");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 520, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Venue");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 550, -1, -1));

        txtUID.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        getContentPane().add(txtUID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 230, 150, -1));

        projectgpa.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        getContentPane().add(projectgpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 580, 125, -1));

        examname.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        examname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                examnameKeyPressed(evt);
            }
        });
        getContentPane().add(examname, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 430, 125, -1));

        examcode.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        examcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                examcodeKeyPressed(evt);
            }
        });
        getContentPane().add(examcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 460, 125, -1));

        examduration.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        examduration.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                examdurationKeyPressed(evt);
            }
        });
        getContentPane().add(examduration, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 520, 125, -1));

        examvenue.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        examvenue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                examvenueKeyPressed(evt);
            }
        });
        getContentPane().add(examvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 550, 125, -1));

        examid.setEditable(false);
        examid.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        getContentPane().add(examid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 400, 125, -1));

        catid.setEditable(false);
        catid.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        getContentPane().add(catid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 400, 125, -1));

        catname.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        catname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                catnameKeyPressed(evt);
            }
        });
        getContentPane().add(catname, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 430, 125, -1));

        catcode.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        catcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                catcodeKeyPressed(evt);
            }
        });
        getContentPane().add(catcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 460, 125, -1));

        catduration.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        catduration.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                catdurationKeyPressed(evt);
            }
        });
        getContentPane().add(catduration, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 521, 125, 20));

        catvenue.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        catvenue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                catvenueKeyPressed(evt);
            }
        });
        getContentPane().add(catvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 550, 125, -1));

        catgpa.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        getContentPane().add(catgpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 580, 125, -1));

        projectid.setEditable(false);
        projectid.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        getContentPane().add(projectid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 400, 125, -1));

        projectname.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        projectname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                projectnameKeyPressed(evt);
            }
        });
        getContentPane().add(projectname, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 430, 125, -1));

        projectcode.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        projectcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                projectcodeKeyPressed(evt);
            }
        });
        getContentPane().add(projectcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 460, 125, -1));

        projectduration.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        projectduration.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                projectdurationKeyPressed(evt);
            }
        });
        getContentPane().add(projectduration, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 520, 125, -1));

        projectvenue.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        projectvenue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                projectvenueKeyPressed(evt);
            }
        });
        getContentPane().add(projectvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 550, 125, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Name");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 430, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Exams");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 360, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("CAT");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 360, -1, -1));

        Update.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update 512,512.png"))); // NOI18N
        Update.setText("   Update");
        Update.setBorderPainted(false);
        Update.setContentAreaFilled(false);
        Update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 650, 170, 40));

        Delete.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete  225,225.png"))); // NOI18N
        Delete.setText("   Delete");
        Delete.setBorderPainted(false);
        Delete.setContentAreaFilled(false);
        Delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 815, 170, 40));

        Refresh.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh 512,512.png"))); // NOI18N
        Refresh.setText("   Refresh Data Table");
        Refresh.setBorderPainted(false);
        Refresh.setContentAreaFilled(false);
        Refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        getContentPane().add(Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 705, 240, 40));

        Clearall.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Clearall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear  512,512.png"))); // NOI18N
        Clearall.setText("  Clear All");
        Clearall.setBorderPainted(false);
        Clearall.setContentAreaFilled(false);
        Clearall.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Clearall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearallActionPerformed(evt);
            }
        });
        getContentPane().add(Clearall, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 760, 170, 40));
        getContentPane().add(catdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 490, 120, -1));
        getContentPane().add(examdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 490, 120, -1));
        getContentPane().add(projectdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 490, 120, -1));

        adminpasswordchange.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        adminpasswordchange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/password change.png"))); // NOI18N
        adminpasswordchange.setText("Change my admin Basics");
        adminpasswordchange.setBorder(null);
        adminpasswordchange.setBorderPainted(false);
        adminpasswordchange.setContentAreaFilled(false);
        adminpasswordchange.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminpasswordchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminpasswordchangeActionPerformed(evt);
            }
        });
        getContentPane().add(adminpasswordchange, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 30, 310, 40));

        Logout7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Logout7.setForeground(new java.awt.Color(51, 51, 255));
        Logout7.setText("Logout");
        Logout7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout7.setMaximumSize(new java.awt.Dimension(100, 50));
        Logout7.setMinimumSize(new java.awt.Dimension(100, 50));
        Logout7.setPreferredSize(new java.awt.Dimension(100, 50));
        Logout7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout7ActionPerformed(evt);
            }
        });
        getContentPane().add(Logout7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 890, 120, 40));

        inquiries.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        inquiries.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inquiry.png"))); // NOI18N
        inquiries.setText("  Investigate Inquiries");
        inquiries.setBorderPainted(false);
        inquiries.setContentAreaFilled(false);
        inquiries.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inquiries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inquiriesActionPerformed(evt);
            }
        });
        getContentPane().add(inquiries, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 30, 310, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Table3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table3MouseClicked
        int SelectedRow=Table3.getSelectedRow();
        String datestring=Table3.getValueAt(SelectedRow, 4).toString();
        DateFormat format=new SimpleDateFormat("yyyy-MM-dd");
        try {
            Date date=format.parse(datestring);
            projectdate.setDate(date);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Error: \n"+ex);
            //JOptionPane.showMessageDialog(this, "Please refresh the System application !    ");
        }
        projectid.setText(Table3.getValueAt(SelectedRow,0).toString());
        projectname.setText(Table3.getValueAt(SelectedRow,2).toString());
        txtUsername.setText(Table3.getValueAt(SelectedRow,1).toString());
        projectcode.setText(Table3.getValueAt(SelectedRow,3).toString());
        projectduration.setText(Table3.getValueAt(SelectedRow,5).toString());
        projectvenue.setText(Table3.getValueAt(SelectedRow,6).toString());
        projectgpa.setText(Table3.getValueAt(SelectedRow,7).toString());
        
        
    }//GEN-LAST:event_Table3MouseClicked

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        //
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed

       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            try{
                DefaultTableModel dtm1=(DefaultTableModel)Table1.getModel();
                dtm1.setRowCount(0);
                DefaultTableModel dtm2=(DefaultTableModel)Table2.getModel();
                dtm2.setRowCount(0);
                DefaultTableModel dtm3=(DefaultTableModel)Table3.getModel();
                dtm3.setRowCount(0);
                Conn.Database.getDatabaseConnection();
                PreparedStatement ps=Conn.Database.con.prepareStatement("Select * from exam where UserName like '%"+txtSearch.getText()+"%'");
                //ps.setString(1,txtSearch.getText());
                ResultSet rs=ps.executeQuery();
                while(rs.next()){
                    Object dataRecord[]={rs.getString("examid"),rs.getString("UserName"),rs.getString("examname"),rs.getString("examcode"),rs.getString("datetime"),rs.getString("timeduration"),rs.getString("venue"),rs.getString("gpa")};
                    dtm1.addRow(dataRecord);
                    }rs.close();ps.close();
                    PreparedStatement ps1=Conn.Database.con.prepareStatement("Select * from cat where UserName like '%"+txtSearch.getText()+"%'");
                    ResultSet rs1=ps1.executeQuery();
                    while(rs1.next()){
                        Object dataRecord1[]={rs1.getString("catid"),rs1.getString("UserName"),rs1.getString("catname"),rs1.getString("catcode"),rs1.getString("datetime"),rs1.getString("timeduration"),rs1.getString("venue"),rs1.getString("gpa")};
                        dtm2.addRow(dataRecord1);
                        }rs1.close();
                        PreparedStatement ps2=Conn.Database.con.prepareStatement("Select * from projects where UserName like '%"+txtSearch.getText()+"%'");
                        
                        ResultSet rs2=ps2.executeQuery();
                        while(rs2.next()){
                            Object dataRecord2[]={rs2.getString("projectid"),rs2.getString("UserName"),rs2.getString("projectname"),rs2.getString("projectcode"),rs2.getString("datetime"),rs2.getString("timeduration"),rs2.getString("venue"),rs2.getString("gpa")};
                            dtm3.addRow(dataRecord2);
                        }rs2.close();
                        PreparedStatement ps3=Conn.Database.con.prepareStatement("Select * from user where UserName like '%"+txtSearch.getText()+"%'");
                   ResultSet rs3=ps3.executeQuery();
                   if(rs3.next()){
                       txtUsername.setText(rs3.getString("username"));
                       txtFullName.setText(rs3.getString("fullname"));
                       txtUID.setText(rs3.getString("uid"));
                       txtemail.setText(rs3.getString("email"));
                       txtmobile.setText(rs3.getString("mobile"));
                   }rs3.close();
                
                if(Table1.getRowCount()<1){
                    JOptionPane.showMessageDialog(this, "No Search Results Found for exams !  ");
                }else if(Table2.getRowCount()<1){
                    JOptionPane.showMessageDialog(this, "No Search Results Found for Assessments !  ");
                }else if(Table3.getRowCount()<1){
                    JOptionPane.showMessageDialog(this, "No Search Results Found for projects !  ");
                }
                Conn.Database.disconnectDatabase();
            }catch(HeadlessException x){
                JOptionPane.showMessageDialog(this, "Error: \n"+x);
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(this, "Error In SQL: \n"+ex);
            }
        }
    }//GEN-LAST:event_txtSearchKeyPressed

    private void examMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examMActionPerformed
        DataManagement e=new DataManagement();
        e.setVisible(true);
        e.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_examMActionPerformed

    private void marksMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marksMActionPerformed
        MarksManagement m=new MarksManagement();
        m.setVisible(true);
        m.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_marksMActionPerformed

    private void paymentsMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentsMActionPerformed
        PaymentsManagement p=new PaymentsManagement();
        p.setVisible(true);
        p.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_paymentsMActionPerformed

    private void fundsMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundsMActionPerformed
        FundsManagement f=new FundsManagement();
        f.setVisible(true);
        f.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_fundsMActionPerformed

    private void salaryMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryMActionPerformed
        SalaryManagement s=new SalaryManagement();
        s.setVisible(true);
        s.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_salaryMActionPerformed

    private void Table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table1MouseClicked
        int SelectedRow=Table1.getSelectedRow();
        String datestring=Table1.getValueAt(SelectedRow, 4).toString();
        DateFormat format=new SimpleDateFormat("yyyy-MM-dd");
        try {
            Date date=format.parse(datestring);
            examdate.setDate(date);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Error: \n"+ex);
            //JOptionPane.showMessageDialog(this, "Please refresh the System application !    ");
        }
        examid.setText(Table1.getValueAt(SelectedRow,0).toString());
        examname.setText(Table1.getValueAt(SelectedRow,2).toString());
        txtUsername.setText(Table1.getValueAt(SelectedRow,1).toString());
        examcode.setText(Table1.getValueAt(SelectedRow,3).toString());
        examduration.setText(Table1.getValueAt(SelectedRow,5).toString());
        examvenue.setText(Table1.getValueAt(SelectedRow,6).toString());
        examgpa.setText(Table1.getValueAt(SelectedRow,7).toString());
        //examdate.setDate(Table1.getValueAt(SelectedRow,7).toString();
        
    }//GEN-LAST:event_Table1MouseClicked

    private void Table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table2MouseClicked
         int SelectedRow=Table2.getSelectedRow();
         String datestring=Table2.getValueAt(SelectedRow, 4).toString();
        DateFormat format=new SimpleDateFormat("yyyy-MM-dd");
         try {
            Date date=format.parse(datestring);
            catdate.setDate(date);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Error: \n"+ex);
            //JOptionPane.showMessageDialog(this, "Please refresh the System application !    ");
        }
          catid.setText(Table2.getValueAt(SelectedRow,0).toString());
        catname.setText(Table2.getValueAt(SelectedRow,2).toString());
        txtUsername.setText(Table2.getValueAt(SelectedRow,1).toString());
        catcode.setText(Table2.getValueAt(SelectedRow,3).toString());
        catduration.setText(Table2.getValueAt(SelectedRow,5).toString());
        catvenue.setText(Table2.getValueAt(SelectedRow,6).toString());
        catgpa.setText(Table2.getValueAt(SelectedRow,7).toString());
    }//GEN-LAST:event_Table2MouseClicked

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtmobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmobileActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        if(txtUsername.getText().length()<1){
            JOptionPane.showMessageDialog(this, "Specific user NOT Selected !   ");
        }else{
            try{
               
                Conn.Database.getDatabaseConnection();
                SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
                if(examcode.getText().isEmpty()){
                    if(catcode.getText().isEmpty()){
                        if(projectcode.getText().isEmpty()){
                            JOptionPane.showMessageDialog(this, "Specific user NOT Selected !   ");
                        }else{
                           PreparedStatement ps2=Conn.Database.con.prepareStatement("Insert into projects(projectname,projectcode,Datetime, timeduration, venue,gpa,username) values(?,?,?,?,?,?,?)");
                           ps2.setString(1, projectname.getText());
                           ps2.setString(2,projectcode.getText());
                           //ps2.setDate(3, (java.sql.Date) projectdate.getDate());
                           String pdate=(String) sdf.format(projectdate.getDate());
                           ps2.setString(3, pdate);
                           ps2.setString(4,projectduration.getText());
                
                           ps2.setString(5,projectvenue.getText());
                           ps2.setDouble(6,Double.valueOf(projectgpa.getText()) );
                           ps2.setString(7,txtUsername.getText());
                           ps2.executeUpdate();
                           JOptionPane.showMessageDialog(this, "Specific multiple data are Updated Successfully !     ");
                        }
                    }else{
                       PreparedStatement ps1=Conn.Database.con.prepareStatement("Insert into cat(catname,catcode,Datetime, timeduration, venue,gpa,username) values(?,?,?,?,?,?,?)");
                           ps1.setString(1, catname.getText());
                           ps1.setString(2,catcode.getText());
                           String cdate=(String) sdf.format(catdate.getDate());
                           ps1.setString(3, cdate);
                           ps1.setString(4,catduration.getText());
                
                           ps1.setString(5,catvenue.getText());
                           ps1.setDouble(6,Double.valueOf(catgpa.getText()) );
                           ps1.setString(7,txtUsername.getText());
                           ps1.executeUpdate();
                           
                           if(projectcode.getText().isEmpty()){
                              JOptionPane.showMessageDialog(this, "Specific multiple data are Updated Successfully !     ");
                           }else{
                           PreparedStatement ps2=Conn.Database.con.prepareStatement("Insert into projects(projectname,projectcode,Datetime, timeduration, venue,gpa,username) values(?,?,?,?,?,?,?)");
                           ps2.setString(1, projectname.getText());
                           ps2.setString(2,projectcode.getText());
                           //ps2.setDate(3, (java.sql.Date) projectdate.getDate());
                           String pdate=(String) sdf.format(projectdate.getDate());
                           ps2.setString(3, pdate);
                           ps2.setString(4,projectduration.getText());
                
                           ps2.setString(5,projectvenue.getText());
                           ps2.setDouble(6,Double.valueOf(projectgpa.getText()) );
                           ps2.setString(7,txtUsername.getText());
                           ps2.executeUpdate();
                           JOptionPane.showMessageDialog(this, "Specific multiple data are Updated Successfully !     ");
                      }
                    }
                }else{
                 PreparedStatement ps=Conn.Database.con.prepareStatement("Insert into exam(examname,examcode,Datetime,timeduration, venue,gpa,username) values(?,?,?,?,?,?,?)");
                           ps.setString(1, examname.getText());
                           ps.setString(2,examcode.getText());
                           //ps.setDate(3, (java.sql.Date) examdate.getDate());
                           String edate=(String) sdf.format(examdate.getDate());
                           ps.setString(3, edate);
                           ps.setString(4,examduration.getText());
                
                           ps.setString(5,examvenue.getText());
                           ps.setDouble(6,Double.valueOf(examgpa.getText()) );
                           ps.setString(7,txtUsername.getText());
                           ps.executeUpdate();
                           
                   if(catcode.getText().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Specific multiple data are Updated Successfully !     ");
                   }else{
                         PreparedStatement ps1=Conn.Database.con.prepareStatement("Insert into cat(catname,catcode,Datetime, timeduration, venue,gpa,username) values(?,?,?,?,?,?,?)");
                           ps1.setString(1, catname.getText());
                           ps1.setString(2,catcode.getText());
                           //ps1.setDate(3, (java.sql.Date) catdate.getDate());
                           String cdate=(String) sdf.format(catdate.getDate());
                           ps1.setString(3, cdate);
                           ps1.setString(4,catduration.getText());
                
                           ps1.setString(5,catvenue.getText());
                           ps1.setDouble(6,Double.valueOf(catgpa.getText()) );
                           ps1.setString(7,txtUsername.getText());
                           ps1.executeUpdate();
                           
                           if(projectcode.getText().isEmpty()){
                              JOptionPane.showMessageDialog(this, "Specific multiple data are Updated Successfully !     ");
                           }else{
                           PreparedStatement ps2=Conn.Database.con.prepareStatement("Insert into projects(projectname,projectcode,Datetime, timeduration, venue,gpa,username) values(?,?,?,?,?,?,?)");
                           ps2.setString(1, projectname.getText());
                           ps2.setString(2,projectcode.getText());
                           //ps2.setDate(3, (java.sql.Date) projectdate.getDate());
                           String pdate=(String) sdf.format(projectdate.getDate());
                           ps2.setString(3, pdate);
                           ps2.setString(4,projectduration.getText());
                
                           ps2.setString(5,projectvenue.getText());
                           ps2.setDouble(6,Double.valueOf(projectgpa.getText()) );
                           ps2.setString(7,txtUsername.getText());
                           ps2.executeUpdate();
                           JOptionPane.showMessageDialog(this, "Specific multiple data are Updated Successfully !     "); 
                      }
                    }
                
                }
                
                //JOptionPane.showMessageDialog(this, "Specific multiple data are Updated Successfully !     ");
                Conn.Database.disconnectDatabase();
            }catch(HeadlessException x){
                JOptionPane.showMessageDialog(this, "Error: \n"+x);
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(this, "Error In SQL: \n"+ex);
            }
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        if(txtUsername.getText().length()<1){
            JOptionPane.showMessageDialog(this, "Specific user NOT Selected !     ");
        }else{
            int option=JOptionPane.showConfirmDialog(this, "Do you want to proceed?       \nNote that all related evaluation data of this user will be deleted !  ", "Confirm", JOptionPane.OK_CANCEL_OPTION);
            if(option==JOptionPane.YES_OPTION){
                try{
                    Conn.Database.getDatabaseConnection();
                    PreparedStatement ps=Conn.Database.con.prepareStatement("delete from exam where Username=?");
                    ps.setString(1,txtUsername.getText());
                    ps.executeUpdate();
                    PreparedStatement ps1=Conn.Database.con.prepareStatement("delete from cat where Username=?");
                    ps1.setString(1,txtUsername.getText());
                    ps1.executeUpdate();
                    PreparedStatement ps2=Conn.Database.con.prepareStatement("delete from projects where Username=?");
                    ps2.setString(1,txtUsername.getText());
                    ps2.executeUpdate();
                    
                    JOptionPane.showMessageDialog(this,"All related multiple data are Deleted Successfully !    ");
                    Conn.Database.disconnectDatabase();

                }catch(HeadlessException x){
                    JOptionPane.showMessageDialog(this, "Error: \n"+x);
                }catch(SQLException ex){
                    JOptionPane.showMessageDialog(this, "Error In SQL: \n"+ex);
                }
            } else{
                JOptionPane.showMessageDialog(this,"Specific data NOT Deleted !    ");
            }
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        try{
            DefaultTableModel dtm=(DefaultTableModel)Table1.getModel();
            dtm.setRowCount(0);
            DefaultTableModel dtm1=(DefaultTableModel)Table2.getModel();
            dtm1.setRowCount(0);
            DefaultTableModel dtm2=(DefaultTableModel)Table3.getModel();
            dtm2.setRowCount(0);
            
            Conn.Database.getDatabaseConnection();
            PreparedStatement ps=Conn.Database.con.prepareStatement("Select * from exam");
            ResultSet rs=ps.executeQuery();

            while(rs.next()){
               
                Object dataRecord[]={rs.getString("examid"),rs.getString("UserName"),rs.getString("examname"),rs.getString("examcode"),rs.getString("datetime"),rs.getString("timeduration"),rs.getString("venue"),rs.getString("gpa")};
                dtm.addRow(dataRecord);
                }rs.close();
                PreparedStatement ps1=Conn.Database.con.prepareStatement("Select * from cat");
                ResultSet rs1=ps1.executeQuery();
                
                while(rs1.next()){
                    Object dataRecord1[]={rs1.getString("catid"),rs1.getString("UserName"),rs1.getString("catname"),rs1.getString("catcode"),rs1.getString("datetime"),rs1.getString("timeduration"),rs1.getString("venue"),rs1.getString("gpa")};
                    dtm1.addRow(dataRecord1);
                    }rs1.close();
                    PreparedStatement ps2=Conn.Database.con.prepareStatement("Select * from projects");
                    ResultSet rs2=ps2.executeQuery();
                while(rs2.next()){
                    Object dataRecord2[]={rs2.getString("projectid"),rs2.getString("UserName"),rs2.getString("projectname"),rs2.getString("projectcode"),rs2.getString("datetime"),rs2.getString("timeduration"),rs2.getString("venue"),rs2.getString("gpa")};
                            dtm2.addRow(dataRecord2);
                }rs2.close();
                
           
            if(Table1.getRowCount()<1){
                JOptionPane.showMessageDialog(this, "No Search Results Found for exams  !    ");
            }
            else if(Table2.getRowCount()<1){
                    JOptionPane.showMessageDialog(this, "No Search Results Found for Assessments !  ");
                }else if(Table3.getRowCount()<1){
                    JOptionPane.showMessageDialog(this, "No Search Results Found for projects !  ");
                }
            Conn.Database.disconnectDatabase();
        }catch(HeadlessException x){
            JOptionPane.showMessageDialog(this, "Error: \n"+x);
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "Error In SQL: \n"+ex);
        }
    }//GEN-LAST:event_RefreshActionPerformed

    private void ClearallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearallActionPerformed
            DefaultTableModel dtm =(DefaultTableModel)Table1.getModel();
            dtm.setRowCount(0);
            DefaultTableModel dtm1=(DefaultTableModel)Table2.getModel();
            dtm1.setRowCount(0);
            DefaultTableModel dtm2=(DefaultTableModel)Table3.getModel();
            dtm2.setRowCount(0);
            Date date1 = new Date ();
        txtSearch.setText("");
        txtUsername.setText("");
        projectgpa.setText("");projectid.setText("");projectname.setText("");projectcode.setText("");projectdate.setDate(date1);/*projectdate.setDate(java.util.Date.from(Instant.MIN)*/;projectduration.setText("");projectvenue.setText("");
        catgpa.setText("");catid.setText("");catname.setText("");catcode.setText("");catdate.setDate(date1);/*catdate.setDate(java.util.Date.from(Instant.MIN))*/;catduration.setText("");catvenue.setText("");
        examgpa.setText("");examid.setText("");examname.setText("");examcode.setText("");examdate.setDate(date1);/*examdate.setDate(java.util.Date.from(Instant.MIN))*/;examduration.setText("");examvenue.setText("");
        txtFullName.setText("");
        txtUID.setText("");
        txtemail.setText("");
        txtmobile.setText("");
        
    }//GEN-LAST:event_ClearallActionPerformed

    private void adminpasswordchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminpasswordchangeActionPerformed
        adminpassword a=new adminpassword();
        a.setVisible(true);
        a.setLocationRelativeTo(null);

    }//GEN-LAST:event_adminpasswordchangeActionPerformed

    private void Logout7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout7ActionPerformed
        int option=JOptionPane.showConfirmDialog(this, "Are you sure to log out? ","Confirm your Decision ",JOptionPane.YES_NO_CANCEL_OPTION);
        if(option==JOptionPane.YES_OPTION){
            Login log=new Login();
            log.setVisible(true);
            log.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_Logout7ActionPerformed

    private void txtUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyPressed

        //
    }//GEN-LAST:event_txtUsernameKeyPressed

    private void examnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_examnameKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN){
            examcode.requestFocus();
        }
    }//GEN-LAST:event_examnameKeyPressed

    private void examcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_examcodeKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN){
            examduration.requestFocus();
        }
    }//GEN-LAST:event_examcodeKeyPressed

    private void examdurationKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_examdurationKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN){
           examvenue.requestFocus();
       }
    }//GEN-LAST:event_examdurationKeyPressed

    private void examvenueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_examvenueKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN){
           examgpa.requestFocus();
       }
    }//GEN-LAST:event_examvenueKeyPressed

    private void catnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_catnameKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN){
           catcode.requestFocus();
       }
    }//GEN-LAST:event_catnameKeyPressed

    private void catcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_catcodeKeyPressed
      if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN){
          catduration.requestFocus();
      }
    }//GEN-LAST:event_catcodeKeyPressed

    private void catdurationKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_catdurationKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN){
           catvenue.requestFocus();
       }
    }//GEN-LAST:event_catdurationKeyPressed

    private void catvenueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_catvenueKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN){
            catgpa.requestFocus();
        }
    }//GEN-LAST:event_catvenueKeyPressed

    private void projectnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_projectnameKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN){
            projectcode.requestFocus();
        }
    }//GEN-LAST:event_projectnameKeyPressed

    private void projectcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_projectcodeKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN){
           projectduration.requestFocus();
       }
    }//GEN-LAST:event_projectcodeKeyPressed

    private void projectdurationKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_projectdurationKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN){
            projectvenue.requestFocus();
        }
    }//GEN-LAST:event_projectdurationKeyPressed

    private void projectvenueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_projectvenueKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN){
            projectgpa.requestFocus();
        }
    }//GEN-LAST:event_projectvenueKeyPressed

    private void inquiriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inquiriesActionPerformed
        inquiries i=new inquiries();
        i.setVisible(true);
       i.setLocationRelativeTo(null);
      this.dispose();
    }//GEN-LAST:event_inquiriesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exammanagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exammanagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exammanagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exammanagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exammanagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clearall;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Logout7;
    private javax.swing.JButton Refresh;
    private javax.swing.JTable Table1;
    private javax.swing.JTable Table2;
    private javax.swing.JTable Table3;
    private javax.swing.JButton Update;
    private javax.swing.JButton adminpasswordchange;
    private javax.swing.JTextField catcode;
    private com.toedter.calendar.JDateChooser catdate;
    private javax.swing.JTextField catduration;
    private javax.swing.JTextField catgpa;
    private javax.swing.JTextField catid;
    private javax.swing.JTextField catname;
    private javax.swing.JTextField catvenue;
    private javax.swing.JLabel clock;
    private javax.swing.JLabel date;
    private javax.swing.JButton examM;
    private javax.swing.JTextField examcode;
    private com.toedter.calendar.JDateChooser examdate;
    private javax.swing.JTextField examduration;
    private javax.swing.JTextField examgpa;
    private javax.swing.JTextField examid;
    private javax.swing.JTextField examname;
    private javax.swing.JTextField examvenue;
    private javax.swing.JButton fundsM;
    private javax.swing.JButton inquiries;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton marksM;
    private javax.swing.JButton paymentsM;
    private javax.swing.JTextField projectcode;
    private com.toedter.calendar.JDateChooser projectdate;
    private javax.swing.JTextField projectduration;
    private javax.swing.JTextField projectgpa;
    private javax.swing.JTextField projectid;
    private javax.swing.JTextField projectname;
    private javax.swing.JTextField projectvenue;
    private javax.swing.JButton salaryM;
    private javax.swing.JLabel titleexam;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtUID;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtmobile;
    // End of variables declaration//GEN-END:variables
}
