/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school;

import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static school.School.M;
import static school.School.Y;
import static school.School.d;
import static school.School.h;
import static school.School.m;
import static school.School.s;

/**
 *
 * @author HP
 */
public class FundsManagement extends javax.swing.JFrame {
    interface Settingzerosh{
       StringBuilder ifelse(int h);
       Settingzerosh doifelseh=(int h) -> {
           StringBuilder HS=new StringBuilder(String.valueOf(h));
           if(HS.length()==1){
               HS.insert(0, "0");
               return HS;
           }else{
              return HS; 
           }
       };
}
 interface Settingzerosm{
       StringBuilder ifelse(int m);
       Settingzerosm doifelsem=(int m) -> {
           StringBuilder MS=new StringBuilder(String.valueOf(m));
           if(MS.length()==1){
               MS.insert(0, "0");
               return MS;
           }else{
              return MS; 
           }
       };
} 
 interface Settingzeross{
       StringBuilder ifelse(int s);
       Settingzeross doifelses=(int s) -> {
           StringBuilder SS=new StringBuilder(String.valueOf(s));
           if(SS.length()==1){
               SS.insert(0, "0");
               return SS;
           }else{
              return SS; 
           }
       };
}
    javax.swing.Timer t=new javax.swing.Timer(1000, new ClockListener());
    class ClockListener implements ActionListener{
            public void actionPerformed(ActionEvent e){
                Calendar now= Calendar.getInstance();
                d=now.get(Calendar.DAY_OF_MONTH);
                M=now.get(Calendar.MONTH);++M;
                Y=now.get(Calendar.YEAR);
                h=now.get(Calendar.HOUR_OF_DAY);
                m=now.get(Calendar.MINUTE);
                s=now.get(Calendar.SECOND);
                StringBuilder HS=Settingzerosh.doifelseh.ifelse(h);
                StringBuilder MS=Settingzerosm.doifelsem.ifelse(m);
                StringBuilder SS=Settingzeross.doifelses.ifelse(s);
                clock.setText(""+HS+":"+MS+":"+SS);
                date.setText(""+d+"/"+M+"/"+Y);
               
    }
    }

    /**
     * Creates new form FundsManagement
     */
    public FundsManagement() {
        initComponents();
        t.start();
        radiostatus.add(radiopaid);
        radiostatus.add(radiounpaid);
        radiounpaid.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radiostatus = new javax.swing.ButtonGroup();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        titlefunds = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        clock = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        salaryM = new javax.swing.JButton();
        examM = new javax.swing.JButton();
        marksM = new javax.swing.JButton();
        paymentsM = new javax.swing.JButton();
        fundsM = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtUID = new javax.swing.JTextField();
        txtFullName = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtmobile = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        fundid = new javax.swing.JTextField();
        semesterno = new javax.swing.JTextField();
        relevantcode = new javax.swing.JTextField();
        fund = new javax.swing.JTextField();
        Update = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();
        Clearall = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        adminpasswordchange = new javax.swing.JButton();
        Logout7 = new javax.swing.JButton();
        inquiries = new javax.swing.JButton();
        radiopaid = new javax.swing.JRadioButton();
        radiounpaid = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fundarizing at UoM");
        setMaximumSize(new java.awt.Dimension(1800, 1000));
        setMinimumSize(new java.awt.Dimension(1800, 1000));
        setPreferredSize(new java.awt.Dimension(1800, 1000));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("University of Moratuwa");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 60));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Wisdom is all wealth");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, 20));

        titlefunds.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        titlefunds.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlefunds.setText("Funds Management");
        getContentPane().add(titlefunds, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 70, 400, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Search");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 100, -1, -1));

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 100, 400, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 140, 550, 10));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText(" All Rights Reserved by UoM");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 900, 160, -1));

        clock.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        clock.setText("00:00:00");
        getContentPane().add(clock, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 875, 60, -1));

        date.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        date.setText("Date");
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(1698, 875, 80, -1));

        salaryM.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        salaryM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salary manage.jpg"))); // NOI18N
        salaryM.setText("Salary Management");
        salaryM.setBorderPainted(false);
        salaryM.setContentAreaFilled(false);
        salaryM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salaryM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryMActionPerformed(evt);
            }
        });
        getContentPane().add(salaryM, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 890, 280, 50));

        examM.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        examM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exam manage.png"))); // NOI18N
        examM.setText(" Exams Management");
        examM.setBorderPainted(false);
        examM.setContentAreaFilled(false);
        examM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        examM.setEnabled(false);
        examM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examMActionPerformed(evt);
            }
        });
        getContentPane().add(examM, new org.netbeans.lib.awtextra.AbsoluteConstraints(1475, 650, 230, 40));

        marksM.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        marksM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/marks manage.png"))); // NOI18N
        marksM.setText(" Marks Management");
        marksM.setBorderPainted(false);
        marksM.setContentAreaFilled(false);
        marksM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        marksM.setEnabled(false);
        marksM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marksMActionPerformed(evt);
            }
        });
        getContentPane().add(marksM, new org.netbeans.lib.awtextra.AbsoluteConstraints(1475, 705, 230, 40));

        paymentsM.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        paymentsM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/payments manage.png"))); // NOI18N
        paymentsM.setText(" Payments Management");
        paymentsM.setBorderPainted(false);
        paymentsM.setContentAreaFilled(false);
        paymentsM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paymentsM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentsMActionPerformed(evt);
            }
        });
        getContentPane().add(paymentsM, new org.netbeans.lib.awtextra.AbsoluteConstraints(1475, 760, 270, 40));

        fundsM.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        fundsM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user management.png"))); // NOI18N
        fundsM.setText(" User Management");
        fundsM.setBorderPainted(false);
        fundsM.setContentAreaFilled(false);
        fundsM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fundsM.setEnabled(false);
        fundsM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundsMActionPerformed(evt);
            }
        });
        getContentPane().add(fundsM, new org.netbeans.lib.awtextra.AbsoluteConstraints(1475, 815, 230, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("User name");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("UID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Full Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 290, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Email  Add");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Mobile No");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 230, -1, -1));

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsernameKeyPressed(evt);
            }
        });
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 170, 150, -1));

        txtUID.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        getContentPane().add(txtUID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 230, 150, -1));

        txtFullName.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        getContentPane().add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 290, 300, -1));

        txtemail.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 170, 150, -1));

        txtmobile.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtmobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmobileActionPerformed(evt);
            }
        });
        getContentPane().add(txtmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 230, 150, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Fund ID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 350, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Semester No");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 380, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Relevant Code");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 410, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Fund LKR");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 440, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Status");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 470, -1, -1));

        fundid.setEditable(false);
        fundid.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        getContentPane().add(fundid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 350, 300, -1));

        semesterno.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        semesterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                semesternoKeyPressed(evt);
            }
        });
        getContentPane().add(semesterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 380, 300, -1));

        relevantcode.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        relevantcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                relevantcodeKeyPressed(evt);
            }
        });
        getContentPane().add(relevantcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 410, 300, -1));

        fund.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        fund.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fundKeyPressed(evt);
            }
        });
        getContentPane().add(fund, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 440, 300, -1));

        Update.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update 512,512.png"))); // NOI18N
        Update.setText("   Update");
        Update.setBorderPainted(false);
        Update.setContentAreaFilled(false);
        Update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 650, 170, 40));

        Refresh.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh 512,512.png"))); // NOI18N
        Refresh.setText("   Refresh Data Table");
        Refresh.setBorderPainted(false);
        Refresh.setContentAreaFilled(false);
        Refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        getContentPane().add(Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 705, 240, 40));

        Clearall.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Clearall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear  512,512.png"))); // NOI18N
        Clearall.setText("  Clear All");
        Clearall.setBorderPainted(false);
        Clearall.setContentAreaFilled(false);
        Clearall.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Clearall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearallActionPerformed(evt);
            }
        });
        getContentPane().add(Clearall, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 760, 170, 40));

        Delete.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete  225,225.png"))); // NOI18N
        Delete.setText("   Delete");
        Delete.setBorderPainted(false);
        Delete.setContentAreaFilled(false);
        Delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 815, 170, 40));

        Table.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fund ID", "User Name", "Semester No", "Relevant Code", "Fund LKR", "Status"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 1140, 410));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/University_of_Moratuwa_logo.png"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, 380));

        adminpasswordchange.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        adminpasswordchange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/password change.png"))); // NOI18N
        adminpasswordchange.setText("Change my admin Basics");
        adminpasswordchange.setBorder(null);
        adminpasswordchange.setBorderPainted(false);
        adminpasswordchange.setContentAreaFilled(false);
        adminpasswordchange.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminpasswordchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminpasswordchangeActionPerformed(evt);
            }
        });
        getContentPane().add(adminpasswordchange, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 30, 310, 40));

        Logout7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Logout7.setForeground(new java.awt.Color(51, 51, 255));
        Logout7.setText("Logout");
        Logout7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout7.setMaximumSize(new java.awt.Dimension(100, 50));
        Logout7.setMinimumSize(new java.awt.Dimension(100, 50));
        Logout7.setPreferredSize(new java.awt.Dimension(100, 50));
        Logout7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout7ActionPerformed(evt);
            }
        });
        getContentPane().add(Logout7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 890, 120, 40));

        inquiries.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        inquiries.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inquiry.png"))); // NOI18N
        inquiries.setText("  Investigate Inquiries");
        inquiries.setBorderPainted(false);
        inquiries.setContentAreaFilled(false);
        inquiries.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inquiries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inquiriesActionPerformed(evt);
            }
        });
        getContentPane().add(inquiries, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 30, 310, 40));

        radiopaid.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radiopaid.setText("Paid");
        getContentPane().add(radiopaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 470, -1, -1));

        radiounpaid.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radiounpaid.setText("Unpaid");
        getContentPane().add(radiounpaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 470, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        //
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed

         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            try{
                DefaultTableModel dtm=(DefaultTableModel)Table.getModel();
                dtm.setRowCount(0);
                String statusname;
                Conn.Database.getDatabaseConnection();
                PreparedStatement ps=Conn.Database.con.prepareStatement("Select * from funds where UserName like '%"+txtSearch.getText()+"%'");
                //ps.setString(1,txtSearch.getText());
                ResultSet rs=ps.executeQuery();
                while(rs.next()){
                    if(rs.getInt("Status")==1){
                        statusname="paid";
                    }else{
                        statusname="unpaid";
                    }
                    PreparedStatement ps1=Conn.Database.con.prepareStatement("Select * from user where UserName like '%"+txtSearch.getText()+"%'");
                    //ps1.setString(1,txtSearch.getText());
                    ResultSet rs1=ps1.executeQuery();
                    if(rs1.next()){
                        txtUsername.setText(rs1.getString("username"));
                        txtFullName.setText(rs1.getString("fullname"));
                        txtUID.setText(rs1.getString("uid"));
                        txtemail.setText(rs1.getString("email"));
                        txtmobile.setText(rs1.getString("mobile"));
                    Object dataRecord[]={rs.getString("fundID"),rs.getString("UserName"),rs.getString("semesterno"),rs.getString("relevantcode"),rs.getString("fund"),statusname};
                    dtm.addRow(dataRecord);
                }
                }rs.close();
                if(Table.getRowCount()<1){
                    JOptionPane.showMessageDialog(this, "No Search Results Found !     ");
                }
                Conn.Database.disconnectDatabase();
            }catch(HeadlessException x){
                JOptionPane.showMessageDialog(this, "Error: \n"+x);
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(this, "Error In SQL: \n"+ex);
            }
        }
    }//GEN-LAST:event_txtSearchKeyPressed

    private void salaryMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryMActionPerformed
        SalaryManagement s=new SalaryManagement();
        s.setVisible(true);
        s.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_salaryMActionPerformed

    private void examMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examMActionPerformed
        Exammanagement e=new Exammanagement();
        e.setVisible(true);
        e.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_examMActionPerformed

    private void marksMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marksMActionPerformed
        MarksManagement m=new MarksManagement();
        m.setVisible(true);
        m.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_marksMActionPerformed

    private void paymentsMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentsMActionPerformed
        PaymentsManagement p=new PaymentsManagement();
        p.setVisible(true);
        p.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_paymentsMActionPerformed

    private void fundsMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundsMActionPerformed
        DataManagement f=new DataManagement();
        f.setVisible(true);
        f.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_fundsMActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtmobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmobileActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        if(txtUsername.getText().length()<1){
            JOptionPane.showMessageDialog(this, "Specific user NOT Selected !   ");
        }else{
            try{
                int statusnumber=0;
            
                if(radiounpaid.isSelected()){
                    statusnumber=0;
                }else if(radiopaid.isSelected()){
                    statusnumber=1;
                }
                Conn.Database.getDatabaseConnection();
                PreparedStatement ps=Conn.Database.con.prepareStatement("Insert into funds(semesterno,relevantcode,fund,status,username) values (?,?,?,?,?)");
                ps.setInt(1,Integer.valueOf(semesterno.getText()));
                ps.setString(2,relevantcode.getText());
                ps.setDouble(3,Double.valueOf(fund.getText()));
                ps.setInt(4,statusnumber);
                ps.setString(5, txtUsername.getText());
                
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Specific data Updated Successfully !     ");
                Conn.Database.disconnectDatabase();
            }catch(HeadlessException x){
                JOptionPane.showMessageDialog(this, "Error: \n"+x);
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(this, "Error In SQL: \n"+ex);
            }
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
       try{
            DefaultTableModel dtm=(DefaultTableModel)Table.getModel();
            dtm.setRowCount(0);
            String statusname;
            Conn.Database.getDatabaseConnection();
            PreparedStatement ps=Conn.Database.con.prepareStatement("Select * from funds");
            ResultSet rs=ps.executeQuery();

            while(rs.next()){
                if(rs.getInt("Status")==1){
                    statusname="paid";
                }else{
                    statusname="unpaid";
                } Object dataRecord[]={rs.getString("fundID"),rs.getString("UserName"),rs.getString("semesterno"),rs.getString("relevantcode"),rs.getString("fund"),statusname};
                dtm.addRow(dataRecord);
            }rs.close();
            if(Table.getRowCount()<1){
                JOptionPane.showMessageDialog(this, "No Search Results Found  !    ");
            }Conn.Database.disconnectDatabase();
        }catch(HeadlessException x){
            JOptionPane.showMessageDialog(this, "Error: \n"+x);
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "Error In SQL: \n"+ex);
        }
    }//GEN-LAST:event_RefreshActionPerformed

    private void ClearallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearallActionPerformed
        DefaultTableModel dtm =(DefaultTableModel)Table.getModel();
        dtm.setRowCount(0);
        txtSearch.setText("");
        txtUsername.setText("");
        txtUID.setText("");
        txtFullName.setText("");
        txtemail.setText("");
        txtmobile.setText("");
        fundid.setText("");
        semesterno.setText("");
        relevantcode.setText("");
        fund.setText("");
        radiounpaid.setSelected(true);
    }//GEN-LAST:event_ClearallActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        if(txtUsername.getText().length()<1){
            JOptionPane.showMessageDialog(this, "Specific user NOT Selected !     ");
        }else{
            int option=JOptionPane.showConfirmDialog(this, "Do you want to proceed?       ", "Confirm", JOptionPane.OK_CANCEL_OPTION);
            if(option==JOptionPane.YES_OPTION){
                try{
                    Conn.Database.getDatabaseConnection();
                    PreparedStatement ps=Conn.Database.con.prepareStatement("delete from funds where Username=?");
                    ps.setString(1,txtUsername.getText());
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this,"Specific data Deleted Successfully !    ");
                    Conn.Database.disconnectDatabase();

                }catch(HeadlessException x){
                    JOptionPane.showMessageDialog(this, "Error: \n"+x);
                }catch(SQLException ex){
                    JOptionPane.showMessageDialog(this, "Error In SQL: \n"+ex);
                }
            } else{
                JOptionPane.showMessageDialog(this,"Specific data NOT Deleted !    ");
            }
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        int SelectedRow=Table.getSelectedRow();
        fundid.setText(Table.getValueAt(SelectedRow,0).toString());
        txtUsername.setText(Table.getValueAt(SelectedRow,1).toString());
        semesterno.setText(Table.getValueAt(SelectedRow,2).toString());
        if(Table.getValueAt(SelectedRow,5).toString().equals("paid")){
            radiopaid.setSelected(true);
        }else if(Table.getValueAt(SelectedRow,5).toString().equals("unpaid")){
           radiounpaid.setSelected(true);
        }
        relevantcode.setText(Table.getValueAt(SelectedRow,3).toString());
        fund.setText(Table.getValueAt(SelectedRow,4).toString());
    }//GEN-LAST:event_TableMouseClicked

    private void adminpasswordchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminpasswordchangeActionPerformed
        adminpassword a=new adminpassword();
        a.setVisible(true);
        a.setLocationRelativeTo(null);

    }//GEN-LAST:event_adminpasswordchangeActionPerformed

    private void Logout7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout7ActionPerformed
        int option=JOptionPane.showConfirmDialog(this, "Are you sure to log out? ","Confirm your Decision ",JOptionPane.YES_NO_CANCEL_OPTION);
        if(option==JOptionPane.YES_OPTION){
            Login log=new Login();
            log.setVisible(true);
            log.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_Logout7ActionPerformed

    private void txtUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN){
            semesterno.requestFocus();
        }
    }//GEN-LAST:event_txtUsernameKeyPressed

    private void semesternoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_semesternoKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN){
           relevantcode.requestFocus();
       }
    }//GEN-LAST:event_semesternoKeyPressed

    private void relevantcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_relevantcodeKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN){
           fund.requestFocus();
       }
    }//GEN-LAST:event_relevantcodeKeyPressed

    private void fundKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fundKeyPressed
      //
    }//GEN-LAST:event_fundKeyPressed

    private void inquiriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inquiriesActionPerformed
        inquiries i=new inquiries();
        i.setVisible(true);
       i.setLocationRelativeTo(null);
       this.dispose();
    }//GEN-LAST:event_inquiriesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FundsManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FundsManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FundsManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FundsManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FundsManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clearall;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Logout7;
    private javax.swing.JButton Refresh;
    private javax.swing.JTable Table;
    private javax.swing.JButton Update;
    private javax.swing.JButton adminpasswordchange;
    private javax.swing.JLabel clock;
    private javax.swing.JLabel date;
    private javax.swing.JButton examM;
    private javax.swing.JTextField fund;
    private javax.swing.JTextField fundid;
    private javax.swing.JButton fundsM;
    private javax.swing.JButton inquiries;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton marksM;
    private javax.swing.JButton paymentsM;
    private javax.swing.JRadioButton radiopaid;
    private javax.swing.ButtonGroup radiostatus;
    private javax.swing.JRadioButton radiounpaid;
    private javax.swing.JTextField relevantcode;
    private javax.swing.JButton salaryM;
    private javax.swing.JTextField semesterno;
    private javax.swing.JLabel titlefunds;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtUID;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtmobile;
    // End of variables declaration//GEN-END:variables
}
