/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Inquiry extends javax.swing.JFrame {

    /**
     * Creates new form Inquiry
     */
    public Inquiry() {
        initComponents();
        set.requestFocus();
        username.setText(School.USERNAME);
        getdetails();
    }
 public void getdetails(){
        try{
            Conn.Database.getDatabaseConnection();
            PreparedStatement ps=Conn.Database.con.prepareStatement("Select * from user where username=?" );
            ps.setString(1,username.getText());
            ResultSet rs=ps.executeQuery();
            if(rs.next()){
                UID.setText(rs.getString("uid"));
                email.setText(rs.getString("email"));
                
            }else{
                JOptionPane.showMessageDialog(this, "Please refresh the system application !   ");
            }
            Conn.Database.disconnectDatabase();
         }catch(HeadlessException x){
               JOptionPane.showMessageDialog(this, "Error: \n"+x);
        }catch(SQLException ex){
               JOptionPane.showMessageDialog(this, "Error In SQL: \n"+ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        UID = new javax.swing.JTextField();
        set = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        data2 = new javax.swing.JTextField();
        types = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        main = new javax.swing.JTextField();
        sub = new javax.swing.JTextField();
        data1 = new javax.swing.JTextField();
        how = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        request = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inquiry Request Form");
        setMaximumSize(new java.awt.Dimension(825, 580));
        setMinimumSize(new java.awt.Dimension(825, 580));
        setPreferredSize(new java.awt.Dimension(825, 580));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("University of Moratuwa");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 24, 390, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Inquiry Request Form");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 220, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel4.setText("UID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 120, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel5.setText("User name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 120, 20));

        UID.setEditable(false);
        UID.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        UID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UIDActionPerformed(evt);
            }
        });
        UID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UIDKeyPressed(evt);
            }
        });
        getContentPane().add(UID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 355, -1));

        set.setEditable(false);
        set.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        set.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        set.setText("Request on any form of modifying the related content of");
        set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setActionPerformed(evt);
            }
        });
        set.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                setKeyPressed(evt);
            }
        });
        getContentPane().add(set, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 215, 355, 25));

        username.setEditable(false);
        username.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameKeyPressed(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 355, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setText("Title*      ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 215, 120, 20));

        data2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        data2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                data2KeyPressed(evt);
            }
        });
        getContentPane().add(data2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 385, 355, 30));

        types.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        types.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Basic Details", "Examinations & Marks", "Payments/Funds or Salary" }));
        types.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                typesFocusLost(evt);
            }
        });
        getContentPane().add(types, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 215, -1, 25));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel8.setText("Email Address");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 120, 20));

        email.setEditable(false);
        email.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailKeyPressed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 355, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setText("Ex. Paid");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel9.setText("Inner Main Theme*");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 120, 20));

        main.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        main.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mainKeyPressed(evt);
            }
        });
        getContentPane().add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 355, -1));

        sub.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        sub.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                subKeyPressed(evt);
            }
        });
        getContentPane().add(sub, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 355, -1));

        data1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        data1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                data1KeyPressed(evt);
            }
        });
        getContentPane().add(data1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 345, 355, 30));

        how.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        how.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Add", "Update", "Delete" }));
        getContentPane().add(how, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 100, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/University_of_Moratuwa_logo.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 50, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setText("Ex. 'Payments' at 'Payments and Funds'");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel11.setText("Type of Change*");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 120, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel13.setText("Generally, relevant notifications and/or changes will be added to the system within one day");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 480, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel14.setText("Data to be changed");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 345, 120, 20));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel15.setText("Ex. 'Paid/Unpaid' at 'Payments'");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel16.setText("Ex. Unpaid");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel17.setText("New data");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 385, 120, 20));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText(" All Rights Reserved by UoM");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 513, 170, 30));

        request.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        request.setForeground(new java.awt.Color(51, 51, 255));
        request.setText("Request Inquiry");
        request.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        request.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestActionPerformed(evt);
            }
        });
        getContentPane().add(request, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 170, 50));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel19.setText("* necessary items");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 435, 120, 20));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel20.setText("Inner Sub Theme");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 120, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UIDActionPerformed

    private void UIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UIDKeyPressed
         //   
    }//GEN-LAST:event_UIDKeyPressed

    private void setKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_setKeyPressed
       //
    }//GEN-LAST:event_setKeyPressed

    private void usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameKeyPressed

    private void emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailKeyPressed

    private void mainKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mainKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN){
        if(main.getText().isEmpty() || main.getText().length()<3){
           JOptionPane.showMessageDialog(this,"Entered inner main theme cannot be accepted, Check and try again !" );
       }else if(types.getSelectedIndex()!=0 || types.getSelectedIndex() != 4){
           sub.requestFocus();
       }else{
           data1.requestFocus();
       }
    }//GEN-LAST:event_mainKeyPressed
    }
    private void subKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_subKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN){
        if((types.getSelectedIndex()!=0 || types.getSelectedIndex() !=4) && sub.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "You have to enter a sub theme related to the selected main theme !");
        }else{
            data1.requestFocus();
        }
    }//GEN-LAST:event_subKeyPressed
    }
    private void requestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestActionPerformed
        if(UID.getText().length()==0 || UID.getText().length()>10 || UID.getText().length()<5){
            JOptionPane.showMessageDialog(this,"Please refresh the System application !" );
        }else if(username.getText().length()<3){
            JOptionPane.showMessageDialog(this,"Please refresh the System application !" );
        }else if(email.getText().length()==0){
            JOptionPane.showMessageDialog(this,"Please refresh the System application !" );
        }else if(main.getText().isEmpty() || main.getText().length()<3){
            JOptionPane.showMessageDialog(this,"Entered inner main theme cannot be accepted, Check and try again !" );
        }else if(types.getSelectedIndex()!=0 && types.getSelectedIndex() !=2 && sub.getText().isEmpty() ){
            JOptionPane.showMessageDialog(this, "You have to enter a sub theme related to the selected main theme !");
        }else if(data1.getText().isEmpty() && how.getSelectedIndex()!=0){
            JOptionPane.showMessageDialog(this, "You have to enter the specific data which you want to change !");
        }else if(data2.getText().isEmpty() && how.getSelectedIndex()!= 2){
            JOptionPane.showMessageDialog(this, "You have to enter the data which you want to apply !");
        }else{
           try{
               Conn.Database.getDatabaseConnection();
               PreparedStatement ps =Conn.Database.con.prepareStatement("Insert into inquiry(username,uid,email,title,main,sub,how,data1,data2,recordtime) values (?,?,?,?,?,?,?,?,?,now()) ");
               ps.setString(1, username.getText());
               ps.setString(2, UID.getText());
               ps.setString(3, email.getText());
               ps.setString(4, types.getSelectedItem().toString());
               ps.setString(5, main.getText());
               ps.setString(6, sub.getText());
               ps.setString(7, how.getSelectedItem().toString());
               ps.setString(8, data1.getText());
               ps.setString(9, data2.getText());
               ps.executeUpdate();
               
               JOptionPane.showMessageDialog(this, "Your Request Inquiry has been successfully submitted !              \nYou will be assisted within one day via your Email address    ");
               this.dispose();
               Conn.Database.disconnectDatabase();
           }catch(HeadlessException x){
           JOptionPane.showMessageDialog(this,"Error:\n"+x);
        }catch(SQLException ex){
           JOptionPane.showMessageDialog(this,"Error In SQL: \n"+ex);
       }  
        }
    }//GEN-LAST:event_requestActionPerformed

    private void data2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_data2KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN){
        if(data2.getText().isEmpty() && how.getSelectedIndex()!= 2){
            JOptionPane.showMessageDialog(this, "You have to enter the data which you want to apply !");
        }else{
            if(UID.getText().length()==0 || UID.getText().length()>10 || UID.getText().length()<5){
            JOptionPane.showMessageDialog(this,"Please refresh the System application !" );
        }else if(username.getText().length()<3){
            JOptionPane.showMessageDialog(this,"Please refresh the System application !" );
        }else if(email.getText().length()==0){
            JOptionPane.showMessageDialog(this,"Please refresh the System application !" );
        }else if(main.getText().isEmpty() || main.getText().length()<3){
            JOptionPane.showMessageDialog(this,"Entered inner main theme cannot be accepted, Check and try again !" );
        }else if(types.getSelectedIndex()!=0 && types.getSelectedIndex() !=2 && sub.getText().isEmpty() ){
            JOptionPane.showMessageDialog(this, "You have to enter a sub theme related to the selected main theme !");
        }else if(data1.getText().isEmpty() && how.getSelectedIndex()!=0){
            JOptionPane.showMessageDialog(this, "You have to enter the specific data which you want to change !");
        }else if(data2.getText().isEmpty() && how.getSelectedIndex()!= 2){
            JOptionPane.showMessageDialog(this, "You have to enter the data which you want to apply !");
        }else{
            try{
               Conn.Database.getDatabaseConnection();
               PreparedStatement ps =Conn.Database.con.prepareStatement("Insert into inquiry(username,uid,email,title,main,sub,how,data1,data2,recordtime) values (?,?,?,?,?,?,?,?,?,now()) ");
               ps.setString(1, username.getText());
               ps.setString(2, UID.getText());
               ps.setString(3, email.getText());
               ps.setString(4, types.getSelectedItem().toString());
               ps.setString(5, main.getText());
               ps.setString(6, sub.getText());
               ps.setString(7, how.getSelectedItem().toString());
               ps.setString(8, data1.getText());
               ps.setString(9, data2.getText());
               ps.executeUpdate();
               JOptionPane.showMessageDialog(this, "Your Request Inquiry has been successfully submitted !  \nYou will be assisted within one day via your Email address    ");
               this.dispose();
               Conn.Database.disconnectDatabase();
           }catch(HeadlessException x){
           JOptionPane.showMessageDialog(this,"Error:\n"+x);
        }catch(SQLException ex){
           JOptionPane.showMessageDialog(this,"Error In SQL: \n"+ex);
       }  
        }
        }
    }//GEN-LAST:event_data2KeyPressed
    }
    private void data1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_data1KeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN){
        if(data1.getText().isEmpty() && how.getSelectedIndex()!=0 ){
           JOptionPane.showMessageDialog(this, "You have to enter the specific data which you want to change !");
       }else{
           data2.requestFocus();
       }
    }//GEN-LAST:event_data1KeyPressed
    }
    private void typesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_typesFocusLost
       main.requestFocus();
    }//GEN-LAST:event_typesFocusLost

    private void setActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inquiry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField UID;
    private javax.swing.JTextField data1;
    private javax.swing.JTextField data2;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox<String> how;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField main;
    private javax.swing.JButton request;
    private javax.swing.JTextField set;
    private javax.swing.JTextField sub;
    private javax.swing.JComboBox<String> types;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
