/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school;

/**
 *
 * @author HP
 */
public class Instantdatasource extends javax.swing.JPanel {

    /**
     * Creates new form Instantdatasource
     */
    public Instantdatasource() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        Logout11 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1800, 1000));
        setPreferredSize(new java.awt.Dimension(1800, 1000));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/University_of_Moratuwa_logo.png"))); // NOI18N
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 10, -1, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("University of Moratuwa");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 50, 350, 60));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Wisdom is all wealth");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 100, -1, 20));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 350, 250, 25));

        Logout11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Logout11.setForeground(new java.awt.Color(51, 51, 255));
        Logout11.setText("Search");
        Logout11.setBorder(null);
        Logout11.setBorderPainted(false);
        Logout11.setContentAreaFilled(false);
        Logout11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout11ActionPerformed(evt);
            }
        });
        add(Logout11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1650, 350, 70, 25));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Instant Data Source");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 275, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void Logout11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Logout11ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
