/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school;

import java.awt.HeadlessException;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static school.Registration.linearResizeBi;

/**
 *
 * @author STUDENT10
 */
public class NewComer extends javax.swing.JFrame {

    /**
     * Creates new form NewComer
     */
    public NewComer() {
        initComponents();
        userName.setText(School.USERNAME);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        Logout7 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UoM welcomes you");
        setMaximumSize(new java.awt.Dimension(800, 580));
        setMinimumSize(new java.awt.Dimension(800, 580));
        setPreferredSize(new java.awt.Dimension(800, 580));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Successfully Registered  !!!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 240, 60));

        Logout.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Logout.setForeground(new java.awt.Color(51, 51, 51));
        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile.png"))); // NOI18N
        Logout.setText("  Go to your Profile");
        Logout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Logout.setBorderPainted(false);
        Logout.setContentAreaFilled(false);
        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.setFocusPainted(false);
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 390, 110));

        Logout7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Logout7.setForeground(new java.awt.Color(51, 51, 255));
        Logout7.setText("Logout");
        Logout7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout7.setMaximumSize(new java.awt.Dimension(100, 50));
        Logout7.setMinimumSize(new java.awt.Dimension(100, 50));
        Logout7.setPreferredSize(new java.awt.Dimension(100, 50));
        Logout7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout7ActionPerformed(evt);
            }
        });
        getContentPane().add(Logout7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 120, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setText("WELCOME TO UNIVERSITY OF MORATUWA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 760, 40));

        userName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        userName.setForeground(new java.awt.Color(51, 51, 255));
        userName.setText("jLabel3");
        getContentPane().add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 290, 40));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText(" All Rights Reserved by UoM");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 513, 170, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/congrats-gif-.gif"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 910, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
          /* try{
               
           Conn.Database.getDatabaseConnection();
           PreparedStatement ps2=Conn.Database.con.prepareStatement("Select photo from user where username=?");
           ps2.setString(1, userName.getText());
           ResultSet rs1=ps1.executeQuery(); 
           if(rs1.next()){
               try {
                   BufferedImage im = ImageIO.read(rs1.getBinaryStream(1));
                   im =linearResizeBi(im, 150, 150);
                   School.image1 = new ImageIcon(im);
                   userphoto.setIcon(School.image1);
                   JOptionPane.showMessageDialog(this,"Welcome to your Home !!!");
                   School.USERNAME=userName.getText();*/
        Welcome w=new Welcome();
        w.setVisible(true);
        w.setLocationRelativeTo(null);
        this.dispose();
        /*Conn.Database.disconnectDatabase();
        }catch(IOException fx){
                    JOptionPane.showMessageDialog(this,"Error In IOException: \n"+fx);
                }
            }else{
               JOptionPane.showMessageDialog(this,"Please refresh the application or exit for a while !  ");
           }
                }
           }catch(HeadlessException x){
           JOptionPane.showMessageDialog(this,"Error:\n"+x);
        }catch(SQLException ex){
           JOptionPane.showMessageDialog(this,"Error In SQL: \n"+ex);
       }
}*/
    }//GEN-LAST:event_LogoutActionPerformed

    private void Logout7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout7ActionPerformed
        Login log=new Login();
        log.setVisible(true);
        log.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_Logout7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewComer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewComer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewComer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewComer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewComer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JButton Logout7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
