/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school;

import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static school.School.M;
import static school.School.Y;
import static school.School.d;
import static school.School.h;
import static school.School.m;
import static school.School.s;

/**
 *
 * @author HP
 */
public class SalaryManagement extends javax.swing.JFrame {
    interface Settingzerosh{
       StringBuilder ifelse(int h);
       Settingzerosh doifelseh=(int h) -> {
           StringBuilder HS=new StringBuilder(String.valueOf(h));
           if(HS.length()==1){
               HS.insert(0, "0");
               return HS;
           }else{
              return HS; 
           }
       };
}
 interface Settingzerosm{
       StringBuilder ifelse(int m);
       Settingzerosm doifelsem=(int m) -> {
           StringBuilder MS=new StringBuilder(String.valueOf(m));
           if(MS.length()==1){
               MS.insert(0, "0");
               return MS;
           }else{
              return MS; 
           }
       };
} 
 interface Settingzeross{
       StringBuilder ifelse(int s);
       Settingzeross doifelses=(int s) -> {
           StringBuilder SS=new StringBuilder(String.valueOf(s));
           if(SS.length()==1){
               SS.insert(0, "0");
               return SS;
           }else{
              return SS; 
           }
       };
}
    javax.swing.Timer t=new javax.swing.Timer(1000, new ClockListener());
    class ClockListener implements ActionListener{
            public void actionPerformed(ActionEvent e){
                Calendar now= Calendar.getInstance();
                d=now.get(Calendar.DAY_OF_MONTH);
                M=now.get(Calendar.MONTH);++M;
                Y=now.get(Calendar.YEAR);
                h=now.get(Calendar.HOUR_OF_DAY);
                m=now.get(Calendar.MINUTE);
                s=now.get(Calendar.SECOND);
                StringBuilder HS=Settingzerosh.doifelseh.ifelse(h);
                StringBuilder MS=Settingzerosm.doifelsem.ifelse(m);
                StringBuilder SS=Settingzeross.doifelses.ifelse(s);
                clock.setText(""+HS+":"+MS+":"+SS);
                date.setText(""+d+"/"+M+"/"+Y);
               
    }
    }

    /**
     * Creates new form SalaryManagement
     */
    public SalaryManagement() {
        initComponents();
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        titlesalary = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        clock = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        salaryM = new javax.swing.JButton();
        examM = new javax.swing.JButton();
        marksM = new javax.swing.JButton();
        paymentsM = new javax.swing.JButton();
        fundsM = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtUID = new javax.swing.JTextField();
        txtFullName = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtmobile = new javax.swing.JTextField();
        totime = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        leavedays = new javax.swing.JTextField();
        basic = new javax.swing.JTextField();
        performance = new javax.swing.JTextField();
        othrs = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        salaryid = new javax.swing.JTextField();
        otperhr = new javax.swing.JTextField();
        bonus = new javax.swing.JTextField();
        tax = new javax.swing.JTextField();
        contribution = new javax.swing.JTextField();
        Update = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();
        Clearall = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        paymentdate = new com.toedter.calendar.JDateChooser();
        fromtime = new com.toedter.calendar.JDateChooser();
        adminpasswordchange = new javax.swing.JButton();
        Logout7 = new javax.swing.JButton();
        inquiries = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Your Salary is managed here");
        setMaximumSize(new java.awt.Dimension(1800, 1000));
        setMinimumSize(new java.awt.Dimension(1800, 1000));
        setPreferredSize(new java.awt.Dimension(1800, 1000));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("University of Moratuwa");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 60));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Wisdom is all wealth");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, 20));

        titlesalary.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        titlesalary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlesalary.setText("Salary Management");
        getContentPane().add(titlesalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 70, 400, 50));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/University_of_Moratuwa_logo.png"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, 380));

        Table.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Salary ID", "User Name", "Payment Date", "From Date", "To Date", "Basic", "othrs", "Performance", "bonus", "leavedays", "tax", "contribution", "otperhr"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 1140, 280));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Search ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 100, -1, -1));

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 100, 400, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 140, 550, 10));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText(" All Rights Reserved by UoM");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 900, 160, -1));

        clock.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        clock.setText("00:00:00");
        getContentPane().add(clock, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 875, 60, -1));

        date.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        date.setText("Date");
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(1698, 875, 80, -1));

        salaryM.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        salaryM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user management.png"))); // NOI18N
        salaryM.setText("User Management");
        salaryM.setBorderPainted(false);
        salaryM.setContentAreaFilled(false);
        salaryM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salaryM.setEnabled(false);
        salaryM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryMActionPerformed(evt);
            }
        });
        getContentPane().add(salaryM, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 890, 280, 50));

        examM.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        examM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exam manage.png"))); // NOI18N
        examM.setText(" Exams Management");
        examM.setBorderPainted(false);
        examM.setContentAreaFilled(false);
        examM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        examM.setEnabled(false);
        examM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examMActionPerformed(evt);
            }
        });
        getContentPane().add(examM, new org.netbeans.lib.awtextra.AbsoluteConstraints(1475, 650, 230, 40));

        marksM.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        marksM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/marks manage.png"))); // NOI18N
        marksM.setText(" Marks Management");
        marksM.setBorderPainted(false);
        marksM.setContentAreaFilled(false);
        marksM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        marksM.setEnabled(false);
        marksM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marksMActionPerformed(evt);
            }
        });
        getContentPane().add(marksM, new org.netbeans.lib.awtextra.AbsoluteConstraints(1475, 705, 230, 40));

        paymentsM.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        paymentsM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/payments manage.png"))); // NOI18N
        paymentsM.setText(" Payments Management");
        paymentsM.setBorderPainted(false);
        paymentsM.setContentAreaFilled(false);
        paymentsM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paymentsM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentsMActionPerformed(evt);
            }
        });
        getContentPane().add(paymentsM, new org.netbeans.lib.awtextra.AbsoluteConstraints(1475, 760, 270, 40));

        fundsM.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        fundsM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fund manage.png"))); // NOI18N
        fundsM.setText(" Funds Management");
        fundsM.setBorderPainted(false);
        fundsM.setContentAreaFilled(false);
        fundsM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fundsM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundsMActionPerformed(evt);
            }
        });
        getContentPane().add(fundsM, new org.netbeans.lib.awtextra.AbsoluteConstraints(1475, 815, 240, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("User name");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("UID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Full Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 290, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Email  Add");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Mobile No");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 230, -1, -1));

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 170, 150, -1));

        txtUID.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        getContentPane().add(txtUID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 230, 150, -1));

        txtFullName.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        getContentPane().add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 290, 300, -1));

        txtemail.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 170, 150, -1));

        txtmobile.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtmobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmobileActionPerformed(evt);
            }
        });
        getContentPane().add(txtmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 230, 150, -1));
        getContentPane().add(totime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 440, 200, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Salary ID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 350, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Payment Date");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 380, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("From Time");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 410, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("To Time");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 440, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Basic");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 470, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Performance");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 500, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Leavedays");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 380, -1, -1));

        leavedays.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        getContentPane().add(leavedays, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 380, 150, -1));

        basic.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        basic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                basicKeyPressed(evt);
            }
        });
        getContentPane().add(basic, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 470, 300, -1));

        performance.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        performance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                performanceKeyPressed(evt);
            }
        });
        getContentPane().add(performance, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 500, 300, -1));

        othrs.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        othrs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                othrsKeyPressed(evt);
            }
        });
        getContentPane().add(othrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 620, 200, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Bonus");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 530, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Taxation %");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 560, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Contribution %");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 590, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("OT hrs");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 620, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("OT per hr");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 350, -1, -1));

        salaryid.setEditable(false);
        salaryid.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        getContentPane().add(salaryid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 350, 200, -1));

        otperhr.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        otperhr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                otperhrKeyPressed(evt);
            }
        });
        getContentPane().add(otperhr, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 350, 150, -1));

        bonus.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        bonus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bonusKeyPressed(evt);
            }
        });
        getContentPane().add(bonus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 530, 300, -1));

        tax.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                taxKeyPressed(evt);
            }
        });
        getContentPane().add(tax, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 560, 200, -1));

        contribution.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        contribution.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contributionKeyPressed(evt);
            }
        });
        getContentPane().add(contribution, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 590, 200, -1));

        Update.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update 512,512.png"))); // NOI18N
        Update.setText("   Update");
        Update.setBorderPainted(false);
        Update.setContentAreaFilled(false);
        Update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 650, 170, 40));

        Refresh.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh 512,512.png"))); // NOI18N
        Refresh.setText("   Refresh Data Table");
        Refresh.setBorderPainted(false);
        Refresh.setContentAreaFilled(false);
        Refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        getContentPane().add(Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 705, 240, 40));

        Clearall.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Clearall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear  512,512.png"))); // NOI18N
        Clearall.setText("  Clear All");
        Clearall.setBorderPainted(false);
        Clearall.setContentAreaFilled(false);
        Clearall.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Clearall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearallActionPerformed(evt);
            }
        });
        getContentPane().add(Clearall, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 760, 170, 40));

        Delete.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete  225,225.png"))); // NOI18N
        Delete.setText("   Delete");
        Delete.setBorderPainted(false);
        Delete.setContentAreaFilled(false);
        Delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 815, 170, 40));
        getContentPane().add(paymentdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 380, 200, -1));
        getContentPane().add(fromtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 410, 200, -1));

        adminpasswordchange.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        adminpasswordchange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/password change.png"))); // NOI18N
        adminpasswordchange.setText("Change my admin Basics");
        adminpasswordchange.setBorder(null);
        adminpasswordchange.setBorderPainted(false);
        adminpasswordchange.setContentAreaFilled(false);
        adminpasswordchange.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminpasswordchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminpasswordchangeActionPerformed(evt);
            }
        });
        getContentPane().add(adminpasswordchange, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 30, 310, 40));

        Logout7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Logout7.setForeground(new java.awt.Color(51, 51, 255));
        Logout7.setText("Logout");
        Logout7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout7.setMaximumSize(new java.awt.Dimension(100, 50));
        Logout7.setMinimumSize(new java.awt.Dimension(100, 50));
        Logout7.setPreferredSize(new java.awt.Dimension(100, 50));
        Logout7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout7ActionPerformed(evt);
            }
        });
        getContentPane().add(Logout7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 890, 120, 40));

        inquiries.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        inquiries.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inquiry.png"))); // NOI18N
        inquiries.setText("  Investigate Inquiries");
        inquiries.setBorderPainted(false);
        inquiries.setContentAreaFilled(false);
        inquiries.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inquiries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inquiriesActionPerformed(evt);
            }
        });
        getContentPane().add(inquiries, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 30, 310, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        int SelectedRow=Table.getSelectedRow();
        salaryid.setText(Table.getValueAt(SelectedRow,0).toString());
        txtUsername.setText(Table.getValueAt(SelectedRow,1).toString());
        String datestring1=Table.getValueAt(SelectedRow, 2).toString();
        String datestring2=Table.getValueAt(SelectedRow, 3).toString();
        String datestring3=Table.getValueAt(SelectedRow, 4).toString();
        DateFormat format=new SimpleDateFormat("yyyy-MM-dd");
         try {
            Date date1=format.parse(datestring1);
            Date date2=format.parse(datestring2);
            Date date3=format.parse(datestring3);
            paymentdate.setDate(date1);
            fromtime.setDate(date2);
            totime.setDate(date3);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Error: \n"+ex);
            //JOptionPane.showMessageDialog(this, "Please refresh the System application !    ");
        }
        //paymentdate.setDate((Date) Table.getValueAt(SelectedRow,2));
       // fromtime.setDate((Date)Table.getValueAt(SelectedRow, 3));
        //totime.setDate((Date)Table.getValueAt(SelectedRow, 4));
        basic.setText(Table.getValueAt(SelectedRow, 5).toString());
        othrs.setText(Table.getValueAt(SelectedRow, 6).toString());
        performance.setText(Table.getValueAt(SelectedRow, 7).toString());
        bonus.setText(Table.getValueAt(SelectedRow, 8).toString());
        leavedays.setText(Table.getValueAt(SelectedRow, 9).toString());
        tax.setText(Table.getValueAt(SelectedRow, 10).toString());
        contribution.setText(Table.getValueAt(SelectedRow, 11).toString());
        otperhr.setText(Table.getValueAt(SelectedRow, 12).toString());
    }//GEN-LAST:event_TableMouseClicked

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        //
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed

        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            try{
                DefaultTableModel dtm=(DefaultTableModel)Table.getModel();
                dtm.setRowCount(0);
                Conn.Database.getDatabaseConnection();
                PreparedStatement ps=Conn.Database.con.prepareStatement("Select * from salary where UserName like '%"+txtSearch.getText()+"%'");
                //ps.setString(1,txtSearch.getText());
                ResultSet rs=ps.executeQuery();
                while(rs.next()){
                    PreparedStatement ps1=Conn.Database.con.prepareStatement("Select * from user where UserName like '%"+txtSearch.getText()+"%'");
                    //ps1.setString(1,txtSearch.getText());
                    ResultSet rs1=ps1.executeQuery();
                    if(rs1.next()){
                        txtUsername.setText(rs1.getString("username"));
                        txtFullName.setText(rs1.getString("fullname"));
                        txtUID.setText(rs1.getString("uid"));
                        txtemail.setText(rs1.getString("email"));
                        txtmobile.setText(rs1.getString("mobile"));
                    Object dataRecord[]={rs.getString("SalaryID"),rs.getString("UserName"),rs.getString("Paymentdate"),rs.getString("fromtime"),rs.getString("totime"),rs.getString("basic"),
                        rs.getString("othrs"),rs.getString("performance"),rs.getString("bonus"),rs.getString("leavedays"),rs.getString("tax"),rs.getString("contribution"),rs.getString("otperhr")};
                    
                    dtm.addRow(dataRecord);
                }
                }rs.close();
                rs.close();ps.close();
                if(Table.getRowCount()<1){
                    JOptionPane.showMessageDialog(this, "No Search Results Found !      ");
                }
                Conn.Database.disconnectDatabase();
            }catch(HeadlessException x){
                JOptionPane.showMessageDialog(this, "Error: \n"+x);
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(this, "Error In SQL: \n"+ex);
            }
        }
    }//GEN-LAST:event_txtSearchKeyPressed

    private void salaryMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryMActionPerformed
        DataManagement s=new DataManagement();
        s.setVisible(true);
        s.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_salaryMActionPerformed

    private void examMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examMActionPerformed
        Exammanagement e=new Exammanagement();
        e.setVisible(true);
        e.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_examMActionPerformed

    private void marksMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marksMActionPerformed
        MarksManagement m=new MarksManagement();
        m.setVisible(true);
        m.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_marksMActionPerformed

    private void paymentsMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentsMActionPerformed
        PaymentsManagement p=new PaymentsManagement();
        p.setVisible(true);
        p.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_paymentsMActionPerformed

    private void fundsMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundsMActionPerformed
        FundsManagement f=new FundsManagement();
        f.setVisible(true);
        f.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_fundsMActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtmobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmobileActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        if(txtUsername.getText().length()<1){
            JOptionPane.showMessageDialog(this, "Specific user NOT Selected !   ");
        }else{
            try{
                
                Conn.Database.getDatabaseConnection();
                SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
                PreparedStatement ps=Conn.Database.con.prepareStatement("Insert into salary(paymentdate,fromtime,totime,basic,othrs,performance,bonus,leavedays,tax,username) values(?,?,?,?,?,?,?,?,?,?)");
                
                String pdate=(String) sdf.format(paymentdate.getDate());
                String pdate1=(String) sdf.format(fromtime.getDate());
                String pdate2=(String) sdf.format(totime.getDate());
                ps.setString(1, pdate);
                ps.setString(2, pdate1);
                ps.setString(3, pdate2);
                ps.setDouble(4,Double.valueOf(basic.getText()));
                ps.setDouble(5,Double.valueOf(othrs.getText()));
                ps.setDouble(6, Double.valueOf(performance.getText()));
                ps.setInt(8,Integer.valueOf(leavedays.getText()));
                ps.setDouble(7,Double.valueOf(bonus.getText()));
                ps.setDouble(9, Double.valueOf(tax.getText()));
                ps.setString(10, txtUsername.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Specific data Updated Successfully !     ");
                Conn.Database.disconnectDatabase();
            }catch(HeadlessException x){
                JOptionPane.showMessageDialog(this, "Error: \n"+x);
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(this, "Error In SQL: \n"+ex);
            }
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        try{
            DefaultTableModel dtm=(DefaultTableModel)Table.getModel();
            dtm.setRowCount(0);
            Conn.Database.getDatabaseConnection();
            PreparedStatement ps=Conn.Database.con.prepareStatement("Select * from salary");
            ResultSet rs=ps.executeQuery();

            while(rs.next()){
                Object dataRecord[]={rs.getString("SalaryID"),rs.getString("UserName"),rs.getString("Paymentdate"),rs.getString("fromtime"),rs.getString("totime"),rs.getString("basic"),rs.getString("othrs"),
                    rs.getString("performance"),rs.getString("bonus"),rs.getString("leavedays"),rs.getString("tax"),rs.getString("contribution"),rs.getString("otperhr")};
                dtm.addRow(dataRecord);
            }
            rs.close();ps.close();
            if(Table.getRowCount()<1){
                JOptionPane.showMessageDialog(this, "No Search Results Found  !    ");
            }Conn.Database.disconnectDatabase();
        }catch(HeadlessException x){
            JOptionPane.showMessageDialog(this, "Error: \n"+x);
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "Error In SQL: \n"+ex);
        }
    
    }//GEN-LAST:event_RefreshActionPerformed

    private void ClearallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearallActionPerformed
        DefaultTableModel dtm =(DefaultTableModel)Table.getModel();
        dtm.setRowCount(0);
        Date date1=new Date();
        txtSearch.setText("");
        txtUsername.setText("");
        txtUID.setText("");
        txtFullName.setText("");
        txtemail.setText("");
        txtmobile.setText("");
        salaryid.setText("");/*paymentdate.setDate(Date.from(Instant.MIN));fromtime.setDate(Date.from(Instant.MIN));totime.setDate(Date.from(Instant.MIN))*/;basic.setText("");
        paymentdate.setDate(date1);fromtime.setDate(date1);totime.setDate(date1);
        othrs.setText("");
        performance.setText("");bonus.setText("");leavedays.setText("");tax.setText("");contribution.setText("");otperhr.setText("");
        
    }//GEN-LAST:event_ClearallActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        if(txtUsername.getText().length()<1){
            JOptionPane.showMessageDialog(this, "Specific user NOT Selected !     ");
        }else{
            int option=JOptionPane.showConfirmDialog(this, "Do you want to proceed?       ", "Confirm", JOptionPane.OK_CANCEL_OPTION);
            if(option==JOptionPane.YES_OPTION){
                try{
                    Conn.Database.getDatabaseConnection();
                    PreparedStatement ps=Conn.Database.con.prepareStatement("delete from salary where Username=?");
                    ps.setString(1,txtUsername.getText());
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this,"Specific data Deleted Successfully !    ");
                    Conn.Database.disconnectDatabase();

                }catch(HeadlessException x){
                    JOptionPane.showMessageDialog(this, "Error: \n"+x);
                }catch(SQLException ex){
                    JOptionPane.showMessageDialog(this, "Error In SQL: \n"+ex);
                }
            } else{
                JOptionPane.showMessageDialog(this,"Specific data NOT Deleted !    ");
            }
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void adminpasswordchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminpasswordchangeActionPerformed
        adminpassword a=new adminpassword();
        a.setVisible(true);
        a.setLocationRelativeTo(null);

    }//GEN-LAST:event_adminpasswordchangeActionPerformed

    private void Logout7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout7ActionPerformed
        int option=JOptionPane.showConfirmDialog(this, "Are you sure to log out? ","Confirm your Decision ",JOptionPane.YES_NO_CANCEL_OPTION);
        if(option==JOptionPane.YES_OPTION){
            Login log=new Login();
            log.setVisible(true);
            log.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_Logout7ActionPerformed

    private void basicKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_basicKeyPressed
      if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN){
          performance.requestFocus();
      }
    }//GEN-LAST:event_basicKeyPressed

    private void performanceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_performanceKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN){
            bonus.requestFocus();
        }
    }//GEN-LAST:event_performanceKeyPressed

    private void bonusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bonusKeyPressed
      if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN){
          tax.requestFocus();
      }
    }//GEN-LAST:event_bonusKeyPressed

    private void taxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taxKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN){
        contribution.requestFocus();
       }
    }//GEN-LAST:event_taxKeyPressed

    private void contributionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contributionKeyPressed
      if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN){
          othrs.requestFocus();
      }
    }//GEN-LAST:event_contributionKeyPressed

    private void othrsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_othrsKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN){
           otperhr.requestFocus();
       }
    }//GEN-LAST:event_othrsKeyPressed

    private void otperhrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_otperhrKeyPressed
      if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN){
          leavedays.requestFocus();
      }
    }//GEN-LAST:event_otperhrKeyPressed

    private void inquiriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inquiriesActionPerformed
        inquiries i=new inquiries();
        i.setVisible(true);
       i.setLocationRelativeTo(null);
       this.dispose();
    }//GEN-LAST:event_inquiriesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalaryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalaryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalaryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalaryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalaryManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clearall;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Logout7;
    private javax.swing.JButton Refresh;
    private javax.swing.JTable Table;
    private javax.swing.JButton Update;
    private javax.swing.JButton adminpasswordchange;
    private javax.swing.JTextField basic;
    private javax.swing.JTextField bonus;
    private javax.swing.JLabel clock;
    private javax.swing.JTextField contribution;
    private javax.swing.JLabel date;
    private javax.swing.JButton examM;
    private com.toedter.calendar.JDateChooser fromtime;
    private javax.swing.JButton fundsM;
    private javax.swing.JButton inquiries;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField leavedays;
    private javax.swing.JButton marksM;
    private javax.swing.JTextField othrs;
    private javax.swing.JTextField otperhr;
    private com.toedter.calendar.JDateChooser paymentdate;
    private javax.swing.JButton paymentsM;
    private javax.swing.JTextField performance;
    private javax.swing.JButton salaryM;
    private javax.swing.JTextField salaryid;
    private javax.swing.JTextField tax;
    private javax.swing.JLabel titlesalary;
    private com.toedter.calendar.JDateChooser totime;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtUID;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtmobile;
    // End of variables declaration//GEN-END:variables
}
